"use client";

// Edit User form — same layout as Create User form (generated by Claude)

import { useState, useEffect, useRef, type FormEvent } from "react";
import { useRouter, useParams } from "next/navigation";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Upload, X } from "lucide-react";
import { ROLES, type User, type Role } from "@/types";

export default function EditUserPage() {
    const router = useRouter();
    const params = useParams();
    const id = params.id as string;
    const avatarInputRef = useRef<HTMLInputElement>(null);

    const [name, setName] = useState("");
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [phone, setPhone] = useState("");
    const [birthday, setBirthday] = useState("");
    const [role, setRole] = useState<Role>("viewer");

    // Avatar state: track the existing URL from the API and any newly selected file
    const [existingAvatarUrl, setExistingAvatarUrl] = useState<string | null>(null);
    const [avatarFile, setAvatarFile] = useState<File | null>(null);
    const [avatarPreview, setAvatarPreview] = useState<string | null>(null);

    const [error, setError] = useState("");
    const [loadingUser, setLoadingUser] = useState(true);
    const [submitting, setSubmitting] = useState(false);

    // Fetch existing user to pre-populate the form
    useEffect(() => {
        api.get<User>(`/users/${id}`)
            .then((u) => {
                setName(u.name);
                setEmail(u.email ?? "");
                setPhone(u.phone ?? "");
                // Birthday from API is an ISO date string — strip to YYYY-MM-DD for the date input
                setBirthday(u.birthday ? u.birthday.slice(0, 10) : "");
                setRole(u.role);
                setExistingAvatarUrl(u.avatar ?? null);
            })
            .catch((err) => {
                setError(err instanceof Error ? err.message : "Failed to load user");
            })
            .finally(() => setLoadingUser(false));
    }, [id]);

    function handleAvatarChange(e: React.ChangeEvent<HTMLInputElement>) {
        const file = e.target.files?.[0];
        if (file) {
            setAvatarFile(file);
            setAvatarPreview(URL.createObjectURL(file));
            setExistingAvatarUrl(null); // new file replaces the existing one
        }
        if (avatarInputRef.current) avatarInputRef.current.value = "";
    }

    function removeAvatar() {
        setAvatarFile(null);
        if (avatarPreview) {
            URL.revokeObjectURL(avatarPreview);
            setAvatarPreview(null);
        }
        setExistingAvatarUrl(null);
    }

    async function handleSubmit(e: FormEvent) {
        e.preventDefault();
        setError("");
        setSubmitting(true);

        try {
            const formData = new FormData();
            formData.append("name", name);
            formData.append("role", role);
            if (email) formData.append("email", email);
            if (phone) formData.append("phone", phone);
            if (birthday) formData.append("birthday", birthday);
            // Only send a new password if the admin typed one
            if (password) formData.append("password", password);
            // Send the new file or the preserved existing URL
            if (avatarFile) {
                formData.append("avatar", avatarFile);
            } else if (existingAvatarUrl) {
                formData.append("avatar", existingAvatarUrl);
            }
            // If both are null, no "avatar" field is sent → backend sets avatar to null

            await api.upload<User>(`/users/${id}`, formData, "PUT");
            router.push("/dashboard/users");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to update user");
        } finally {
            setSubmitting(false);
        }
    }

    if (loadingUser) {
        return (
            <div className="flex min-h-[60vh] items-center justify-center p-6">
                <p className="text-muted-foreground">Loading...</p>
            </div>
        );
    }

    // Fatal load error — user data never arrived
    if (error && !name) {
        return (
            <div className="p-6">
                <p className="text-sm text-destructive">{error}</p>
            </div>
        );
    }

    // The currently visible avatar preview: newly picked file takes priority, then existing URL
    const shownPreview = avatarPreview ?? existingAvatarUrl;

    return (
        <div className="p-6">
            <div className="mx-auto max-w-2xl">
                <Card>
                    <CardHeader>
                        <CardTitle className="text-2xl">Edit User</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={handleSubmit} className="flex flex-col gap-5">
                            {/* Name */}
                            <div className="flex flex-col gap-2">
                                <Label htmlFor="name">Name *</Label>
                                <Input
                                    id="name"
                                    placeholder="e.g. John Doe"
                                    value={name}
                                    onChange={(e) => setName(e.target.value)}
                                    required
                                />
                            </div>

                            {/* Email */}
                            <div className="flex flex-col gap-2">
                                <Label htmlFor="email">Email</Label>
                                <Input
                                    id="email"
                                    type="email"
                                    placeholder="e.g. john@example.com"
                                    value={email}
                                    onChange={(e) => setEmail(e.target.value)}
                                />
                            </div>

                            {/* Password — optional on edit */}
                            <div className="flex flex-col gap-2">
                                <Label htmlFor="password">New Password (leave blank to keep current)</Label>
                                <Input
                                    id="password"
                                    type="password"
                                    placeholder="Enter a new password"
                                    value={password}
                                    onChange={(e) => setPassword(e.target.value)}
                                />
                            </div>

                            {/* Phone */}
                            <div className="flex flex-col gap-2">
                                <Label htmlFor="phone">Phone</Label>
                                <Input
                                    id="phone"
                                    type="tel"
                                    placeholder="e.g. 555-123-4567"
                                    value={phone}
                                    onChange={(e) => setPhone(e.target.value)}
                                />
                            </div>

                            {/* Birthday */}
                            <div className="flex flex-col gap-2">
                                <Label htmlFor="birthday">Birthday</Label>
                                <Input
                                    id="birthday"
                                    type="date"
                                    value={birthday}
                                    onChange={(e) => setBirthday(e.target.value)}
                                />
                            </div>

                            {/* Role — options derived from ROLES constant */}
                            <div className="flex flex-col gap-2">
                                <Label htmlFor="role">Role *</Label>
                                <select
                                    id="role"
                                    value={role}
                                    onChange={(e) => setRole(e.target.value as Role)}
                                    className="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
                                    required
                                >
                                    {ROLES.map((r) => (
                                        <option key={r} value={r}>
                                            {r.charAt(0).toUpperCase() + r.slice(1)}
                                        </option>
                                    ))}
                                </select>
                            </div>

                            {/* Avatar */}
                            <div className="flex flex-col gap-2">
                                <Label>Avatar</Label>
                                {shownPreview ? (
                                    <div className="flex items-center gap-4">
                                        <img
                                            src={shownPreview}
                                            alt="Avatar preview"
                                            className="h-20 w-20 rounded-full object-cover border"
                                        />
                                        <button
                                            type="button"
                                            onClick={removeAvatar}
                                            className="rounded p-1 text-muted-foreground hover:text-destructive"
                                        >
                                            <X className="h-5 w-5" />
                                        </button>
                                    </div>
                                ) : (
                                    <div
                                        className="flex cursor-pointer flex-col items-center gap-2 rounded-lg border-2 border-dashed border-muted-foreground/30 p-6 transition-colors hover:border-muted-foreground/50"
                                        onClick={() => avatarInputRef.current?.click()}
                                    >
                                        <Upload className="h-8 w-8 text-muted-foreground" />
                                        <p className="text-sm text-muted-foreground">
                                            Click to upload an avatar image
                                        </p>
                                    </div>
                                )}
                                <input
                                    ref={avatarInputRef}
                                    type="file"
                                    accept="image/*"
                                    className="hidden"
                                    onChange={handleAvatarChange}
                                />
                            </div>

                            {/* Error */}
                            {error && (
                                <p className="text-sm text-destructive">{error}</p>
                            )}

                            {/* Actions */}
                            <div className="flex gap-3 pt-2">
                                <Button type="submit" disabled={submitting}>
                                    {submitting ? "Saving..." : "Save"}
                                </Button>
                                <Button
                                    type="button"
                                    variant="outline"
                                    onClick={() => router.push("/dashboard/users")}
                                    disabled={submitting}
                                >
                                    Cancel
                                </Button>
                            </div>
                        </form>
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}
