"use client";

// Breadcrumb component (generated by Claude)
// Shows the current folder path as "Files / Parent / Current".
// At root (folderId === null) it just renders "Files".

import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { ChevronRight } from "lucide-react";

interface Ancestor {
    id: number;
    title: string;
}

interface BreadcrumbProps {
    folderId: string | null;
}

export default function Breadcrumb({ folderId }: BreadcrumbProps) {
    const [ancestors, setAncestors] = useState<Ancestor[]>([]);
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (!folderId) {
            setAncestors([]);
            return;
        }
        let cancelled = false;
        setLoading(true);
        api.get<Ancestor[]>(`/collections/${folderId}/ancestors`)
            .then((data) => {
                if (!cancelled) setAncestors(data);
            })
            .catch(() => {
                if (!cancelled) setAncestors([]);
            })
            .finally(() => {
                if (!cancelled) setLoading(false);
            });
            
        return () => {
            cancelled = true;
        };
    }, [folderId]);

    // At root: just "Files"
    if (!folderId) {
        return <h1 className="text-2xl font-bold">Files</h1>;
    }

    // Loading: keep layout stable by showing just "Files" while ancestors load
    if (loading || ancestors.length === 0) {
        return (
            <div className="flex items-center gap-2 text-2xl font-bold">
                <Link href="/dashboard/files" className="hover:underline">
                    Files
                </Link>
            </div>
        );
    }

    // The final ancestor is the current folder (non-link); all prior are links.
    const trail = ancestors.slice(0, -1);
    const current = ancestors[ancestors.length - 1];

    return (
        <div className="flex flex-wrap items-center gap-2 text-2xl font-bold">
            <Link href="/dashboard/files" className="hover:underline">
                Files
            </Link>
            {trail.map((a) => (
                <span key={a.id} className="flex items-center gap-2">
                    <ChevronRight className="h-5 w-5 text-muted-foreground" />
                    <Link
                        href={`/dashboard/files?folder=${a.id}`}
                        className="hover:underline"
                    >
                        {a.title}
                    </Link>
                </span>
            ))}
            <ChevronRight className="h-5 w-5 text-muted-foreground" />
            <span>{current.title}</span>
        </div>
    );
}