"use client";

// ItemCard component (generated by Claude)
// Displays a single item with inline title editing.
// Edit UX matches the "create new folder" card — Input + check/X buttons.

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { FileText, Pencil, Trash2, Check, X } from "lucide-react";
import { useAuth } from "@/lib/auth";
import type { Item } from "@/types";

interface ItemCardProps {
    item: Item;
    onDelete: (id: number) => void;
    onEdit: (id: number, newTitle: string) => Promise<void>;
}

export default function ItemCard({ item, onDelete, onEdit }: ItemCardProps) {
    const { user } = useAuth();
    const [isEditing, setIsEditing] = useState(false);
    const [editTitle, setEditTitle] = useState(item.title);

    const canModify =
        !!user &&
        (user.role === "admin" ||
            (user.role === "editor" && item.owner_id === user.id));

    async function handleSubmit(e: FormEvent) {
        e.preventDefault();
        try {
            await onEdit(item.id, editTitle);
            setIsEditing(false);
        } catch {
            // parent handles error; stay in edit mode
        }
    }

    function handleCancel() {
        setEditTitle(item.title);
        setIsEditing(false);
    }

    return (
        <Card className="transition-colors hover:bg-muted/50">
            <CardContent className="flex items-center justify-between gap-3 p-4">
                {isEditing ? (
                    <div className="flex flex-1 items-center gap-3">
                        <FileText className="h-5 w-5 shrink-0 text-muted-foreground" />
                        <form onSubmit={handleSubmit} className="flex flex-1 items-center gap-2">
                            <Input
                                value={editTitle}
                                onChange={(e) => setEditTitle(e.target.value)}
                                required
                            />
                            <button
                                type="submit"
                                className="shrink-0 rounded p-1 text-muted-foreground hover:text-foreground"
                            >
                                <Check className="h-4 w-4" />
                            </button>
                            <button
                                type="button"
                                onClick={handleCancel}
                                className="shrink-0 rounded p-1 text-muted-foreground hover:text-destructive"
                            >
                                <X className="h-4 w-4" />
                            </button>
                        </form>
                    </div>
                ) : (
                    <>
                        <Link
                            href={`/dashboard/files/${item.id}`}
                            className="flex min-w-0 flex-1 items-center gap-3"
                        >
                            <FileText className="h-5 w-5 shrink-0 text-muted-foreground" />
                            <span className="truncate font-medium">{item.title}</span>
                        </Link>
                        {canModify && (
                            <div className="flex gap-2">
                                <button
                                    onClick={() => setIsEditing(true)}
                                    className="shrink-0 rounded p-1 text-muted-foreground hover:text-foreground"
                                >
                                    <Pencil className="h-4 w-4" />
                                </button>
                                <button
                                    onClick={() => onDelete(item.id)}
                                    className="shrink-0 rounded p-1 text-muted-foreground hover:text-destructive"
                                >
                                    <Trash2 className="h-4 w-4" />
                                </button>
                            </div>
                        )}
                    </>
                )}
            </CardContent>
        </Card>
    );
}