"use client";

// Self profile page — view by default, toggles to edit on demand (generated by Claude)

import { useState, useEffect, useRef, type FormEvent } from "react";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Upload, X } from "lucide-react";
import type { User } from "@/types";

export default function MePage() {
    const { user: authUser, updateUser } = useAuth();
    const avatarInputRef = useRef<HTMLInputElement>(null);

    // Snapshot of the last-saved user — used to revert on Cancel
    const [originalUser, setOriginalUser] = useState<User | null>(null);

    const [name, setName] = useState("");
    const [email, setEmail] = useState("");
    const [password, setPassword] = useState("");
    const [phone, setPhone] = useState("");
    const [birthday, setBirthday] = useState("");

    // Avatar state — same pattern as the admin edit form: track existing URL + any new file
    const [existingAvatarUrl, setExistingAvatarUrl] = useState<string | null>(null);
    const [avatarFile, setAvatarFile] = useState<File | null>(null);
    const [avatarPreview, setAvatarPreview] = useState<string | null>(null);

    const [isEditing, setIsEditing] = useState(false);
    const [error, setError] = useState("");
    const [success, setSuccess] = useState("");
    const [loadingUser, setLoadingUser] = useState(true);
    const [submitting, setSubmitting] = useState(false);

    // Layout already redirects to /login if there's no user, but guard for the type
    const userId = authUser?.id;

    // Populate form state from a full user object (used on initial load and after save)
    function hydrateFromUser(u: User) {
        setName(u.name);
        setEmail(u.email ?? "");
        setPhone(u.phone ?? "");
        setBirthday(u.birthday ? u.birthday.slice(0, 10) : "");
        setExistingAvatarUrl(u.avatar ?? null);
        setAvatarFile(null);
        setAvatarPreview(null);
        setPassword("");
    }

    // Fetch full user on mount — login response is partial (no phone/birthday/avatar)
    useEffect(() => {
        if (!userId) return;
        api.get<User>(`/users/${userId}`)
            .then((u) => {
                setOriginalUser(u);
                hydrateFromUser(u);
            })
            .catch((err) => {
                setError(err instanceof Error ? err.message : "Failed to load profile");
            })
            .finally(() => setLoadingUser(false));
    }, [userId]);

    function handleAvatarChange(e: React.ChangeEvent<HTMLInputElement>) {
        const file = e.target.files?.[0];
        if (file) {
            setAvatarFile(file);
            setAvatarPreview(URL.createObjectURL(file));
            setExistingAvatarUrl(null);
        }
        if (avatarInputRef.current) avatarInputRef.current.value = "";
    }

    function removeAvatar() {
        setAvatarFile(null);
        if (avatarPreview) {
            URL.revokeObjectURL(avatarPreview);
            setAvatarPreview(null);
        }
        setExistingAvatarUrl(null);
    }

    function handleEditClick() {
        setError("");
        setSuccess("");
        setIsEditing(true);
    }

    function handleCancel() {
        if (originalUser) hydrateFromUser(originalUser);
        setError("");
        setIsEditing(false);
    }

    async function handleSubmit(e: FormEvent) {
        e.preventDefault();
        if (!userId) return;
        setError("");
        setSuccess("");
        setSubmitting(true);

        try {
            const formData = new FormData();
            formData.append("name", name);
            if (email) formData.append("email", email);
            if (phone) formData.append("phone", phone);
            if (birthday) formData.append("birthday", birthday);
            // Only send password if user typed a new one
            if (password) formData.append("password", password);
            // Send the new file or preserve the existing URL; if both null, backend clears the avatar
            if (avatarFile) {
                formData.append("avatar", avatarFile);
            } else if (existingAvatarUrl) {
                formData.append("avatar", existingAvatarUrl);
            }
            // Send role unchanged — backend requires it (NOT NULL ENUM column).
            // Reading from originalUser (not a form field) ensures the user cannot self-promote.
            if (originalUser) formData.append("role", originalUser.role);

            const updated = await api.upload<User>(`/users/${userId}`, formData, "PUT");
            setOriginalUser(updated);
            hydrateFromUser(updated);
            updateUser(updated); // sync sidebar avatar/name immediately
            setIsEditing(false);
            setSuccess("Profile updated");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to update profile");
        } finally {
            setSubmitting(false);
        }
    }

    if (loadingUser) {
        return (
            <div className="flex min-h-[60vh] items-center justify-center p-6">
                <p className="text-muted-foreground">Loading...</p>
            </div>
        );
    }

    // Fatal load error — never got the user data
    if (error && !originalUser) {
        return (
            <div className="p-6">
                <p className="text-sm text-destructive">{error}</p>
            </div>
        );
    }

    // Newly picked file takes priority for preview, then existing URL
    const shownAvatar = avatarPreview ?? existingAvatarUrl;
    const initials = name
        .split(" ")
        .map((n) => n[0])
        .join("")
        .toUpperCase()
        .slice(0, 2);

    return (
        <div className="p-6">
            <div className="mx-auto max-w-2xl">
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between">
                        <CardTitle className="text-2xl">My Profile</CardTitle>
                        {!isEditing && (
                            <Button onClick={handleEditClick} variant="outline">
                                Edit
                            </Button>
                        )}
                    </CardHeader>
                    <CardContent>
                        {isEditing ? (
                            // ── Edit mode ──
                            <form onSubmit={handleSubmit} className="flex flex-col gap-5">
                                {/* Name */}
                                <div className="flex flex-col gap-2">
                                    <Label htmlFor="name">Name *</Label>
                                    <Input
                                        id="name"
                                        value={name}
                                        onChange={(e) => setName(e.target.value)}
                                        required
                                    />
                                </div>

                                {/* Email */}
                                <div className="flex flex-col gap-2">
                                    <Label htmlFor="email">Email</Label>
                                    <Input
                                        id="email"
                                        type="email"
                                        value={email}
                                        onChange={(e) => setEmail(e.target.value)}
                                    />
                                </div>

                                {/* Password — optional */}
                                <div className="flex flex-col gap-2">
                                    <Label htmlFor="password">
                                        New Password (leave blank to keep current)
                                    </Label>
                                    <Input
                                        id="password"
                                        type="password"
                                        placeholder="Enter a new password"
                                        value={password}
                                        onChange={(e) => setPassword(e.target.value)}
                                    />
                                </div>

                                {/* Phone */}
                                <div className="flex flex-col gap-2">
                                    <Label htmlFor="phone">Phone</Label>
                                    <Input
                                        id="phone"
                                        type="tel"
                                        value={phone}
                                        onChange={(e) => setPhone(e.target.value)}
                                    />
                                </div>

                                {/* Birthday */}
                                <div className="flex flex-col gap-2">
                                    <Label htmlFor="birthday">Birthday</Label>
                                    <Input
                                        id="birthday"
                                        type="date"
                                        value={birthday}
                                        onChange={(e) => setBirthday(e.target.value)}
                                    />
                                </div>

                                {/* Role — always read-only, never an input */}
                                <div className="flex flex-col gap-2">
                                    <Label>Role</Label>
                                    <p className="text-sm capitalize text-muted-foreground">
                                        {originalUser?.role}
                                    </p>
                                </div>

                                {/* Avatar */}
                                <div className="flex flex-col gap-2">
                                    <Label>Avatar</Label>
                                    {shownAvatar ? (
                                        <div className="flex items-center gap-4">
                                            <img
                                                src={shownAvatar}
                                                alt="Avatar preview"
                                                className="h-20 w-20 rounded-full object-cover border"
                                            />
                                            <button
                                                type="button"
                                                onClick={removeAvatar}
                                                className="rounded p-1 text-muted-foreground hover:text-destructive"
                                            >
                                                <X className="h-5 w-5" />
                                            </button>
                                        </div>
                                    ) : (
                                        <div
                                            className="flex cursor-pointer flex-col items-center gap-2 rounded-lg border-2 border-dashed border-muted-foreground/30 p-6 transition-colors hover:border-muted-foreground/50"
                                            onClick={() => avatarInputRef.current?.click()}
                                        >
                                            <Upload className="h-8 w-8 text-muted-foreground" />
                                            <p className="text-sm text-muted-foreground">
                                                Click to upload an avatar image
                                            </p>
                                        </div>
                                    )}
                                    <input
                                        ref={avatarInputRef}
                                        type="file"
                                        accept="image/*"
                                        className="hidden"
                                        onChange={handleAvatarChange}
                                    />
                                </div>

                                {error && (
                                    <p className="text-sm text-destructive">{error}</p>
                                )}

                                <div className="flex gap-3 pt-2">
                                    <Button type="submit" disabled={submitting}>
                                        {submitting ? "Saving..." : "Save"}
                                    </Button>
                                    <Button
                                        type="button"
                                        variant="outline"
                                        onClick={handleCancel}
                                        disabled={submitting}
                                    >
                                        Cancel
                                    </Button>
                                </div>
                            </form>
                        ) : (
                            // ── View mode ──
                            <div className="flex flex-col gap-5">
                                {/* Avatar */}
                                <div className="flex justify-center pt-2">
                                    <Avatar className="h-24 w-24">
                                        {existingAvatarUrl && (
                                            <AvatarImage src={existingAvatarUrl} alt={name} />
                                        )}
                                        <AvatarFallback className="text-2xl">
                                            {initials}
                                        </AvatarFallback>
                                    </Avatar>
                                </div>

                                <ProfileRow label="Name" value={name} />
                                <ProfileRow label="Email" value={email || "—"} />
                                <ProfileRow label="Phone" value={phone || "—"} />
                                <ProfileRow label="Birthday" value={birthday || "—"} />
                                <div className="flex flex-col gap-1">
                                    <Label>Role</Label>
                                    <p className="text-sm capitalize">
                                        {originalUser?.role}
                                    </p>
                                </div>

                                {success && (
                                    <p className="text-sm text-green-600">{success}</p>
                                )}
                            </div>
                        )}
                    </CardContent>
                </Card>
            </div>
        </div>
    );
}

// Read-only label/value row for view mode (generated by Claude)
function ProfileRow({ label, value }: { label: string; value: string }) {
    return (
        <div className="flex flex-col gap-1">
            <Label>{label}</Label>
            <p className="text-sm">{value}</p>
        </div>
    );
}
