'use client'

import { useEffect, useState, useCallback } from "react";
import { useTranslations, useFormatter } from "next-intl";
import { api } from "@/lib/api";
import Link from "next/link";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button, buttonVariants } from "@/components/ui/button";
import { Upload, Pencil, Trash2 } from "lucide-react";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import type { User } from "@/types";
import { useAuth } from "@/lib/auth";

export default function UsersPage() {
    const { user } = useAuth();
    const [users, setUsers] = useState<User[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    // i18n: page namespace + Common + Roles for the role column + locale-aware date (generated by Claude)
    const t = useTranslations("Users");
    const tc = useTranslations("Common");
    const tr = useTranslations("Roles");
    const format = useFormatter();

    const canEditUsers = user?.role === "admin";
    const [deletingId, setDeletingId] = useState<number | null>(null);

    const fetchUsers = useCallback(async () => {
        try {
            const data = await api.get<User[]>("/users");
            setUsers(data);
            setError("");
        } catch (err) {
            setError(err instanceof Error ? err.message : t("failedLoad"));
        } finally {
            setLoading(false);
        }
    }, [t]);

    async function handleDelete(id: number, name: string) {
        if (!confirm(t("deleteConfirm", { name }))) return;
        setDeletingId(id);
        try {
            await api.delete(`/users/${id}`);
            setUsers((prev) => prev.filter((u) => u.id !== id));
        } catch (err) {
            setError(err instanceof Error ? err.message : t("failedDelete"));
        } finally {
            setDeletingId(null);
        }
    }

    useEffect(() => {
        fetchUsers();
    }, [fetchUsers]);

    if (loading) {
        return (
            <div className="flex min-h-[60vh] items-center justify-center p-6">
                <p className="text-muted-foreground">{tc("loading")}</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="p-6">
                <p className="text-sm text-destructive">{error}</p>
            </div>
        );
    }

    return (
        <div className="p-6">
            {/* Header */}
            <div className="mb-4 flex items-center gap-4">
                <h1 className="text-2xl font-bold">{t("title")}</h1>
                {canEditUsers && (
                    <Link
                        href="/dashboard/users/create"
                        className={buttonVariants({ variant: "outline", size: "sm", className: "gap-2" })}
                    >
                        <Upload className="h-4 w-4" />
                        {t("createNew")}
                    </Link>
                )}
            </div>

            {/* Users table (generated by Claude) */}
            <div className="rounded-lg border">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>{t("colUser")}</TableHead>
                            <TableHead>{t("colRole")}</TableHead>
                            <TableHead>{t("colEmail")}</TableHead>
                            <TableHead>{t("colPhone")}</TableHead>
                            <TableHead>{t("colBirthday")}</TableHead>
                            {canEditUsers && <TableHead className="w-20" />}
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {users.map((u) => {
                            const initials = u.name
                                .split(" ")
                                .map((n) => n[0])
                                .join("")
                                .toUpperCase()
                                .slice(0, 2);

                            return (
                                <TableRow key={u.id}>
                                    <TableCell>
                                        <div className="flex items-center gap-3">
                                            <Avatar className="h-8 w-8 rounded-full overflow-clip">
                                                {
                                                    u.avatar != null ? (
                                                        <img className="w-full h-full object-cover" src={`${u.avatar}`} />
                                                    ) : (
                                                        <AvatarFallback className="text-xs">
                                                            {initials}
                                                        </AvatarFallback>
                                                    )
                                                }

                                            </Avatar>
                                            <span className="font-medium">{u.name}</span>
                                        </div>
                                    </TableCell>
                                    <TableCell>{tr(u.role)}</TableCell>
                                    <TableCell>{u.email}</TableCell>
                                    <TableCell>{u.phone || tc("dash")}</TableCell>
                                    <TableCell>
                                        {u.birthday
                                            ? format.dateTime(new Date(u.birthday), { dateStyle: "medium" })
                                            : tc("dash")}
                                    </TableCell>
                                    {/* Edit and delete actions — admin only (generated by Claude) */}
                                    {canEditUsers && (
                                        <TableCell>
                                            <div className="flex items-center gap-1">
                                                <Link
                                                    href={`/dashboard/users/edit/${u.id}`}
                                                    className={buttonVariants({ variant: "ghost", size: "icon" })}
                                                >
                                                    <Pencil className="h-4 w-4" />
                                                </Link>
                                                <Button
                                                    variant="ghost"
                                                    size="icon"
                                                    disabled={deletingId === u.id}
                                                    onClick={() => handleDelete(u.id, u.name)}
                                                    className="text-muted-foreground hover:text-destructive"
                                                >
                                                    <Trash2 className="h-4 w-4" />
                                                </Button>
                                            </div>
                                        </TableCell>
                                    )}
                                </TableRow>
                            );
                        })}
                    </TableBody>
                </Table>
            </div>
        </div>
    );
}
