'use client'

import { useEffect, useState, useCallback } from "react";
import { api } from "@/lib/api";
import Link from "next/link";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { buttonVariants } from "@/components/ui/button";
import { Upload, CheckCircle, X, FileText, Trash2 } from "lucide-react";
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
} from "@/components/ui/table";
import type { User } from "@/types";
import { useAuth } from "@/lib/auth";

export default function UsersPage() {
    const { user } = useAuth();
    const [users, setUsers] = useState<User[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    const canEditUsers = user?.role === "admin";

    const fetchUsers = useCallback(async () => {
        try {
            const data = await api.get<User[]>("/users");
            setUsers(data);
            setError("");
        } catch (err) {
            setError(err instanceof Error ? err.message : "Failed to load users");
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        fetchUsers();
    }, [fetchUsers]);

    if (loading) {
        return (
            <div className="flex min-h-[60vh] items-center justify-center p-6">
                <p className="text-muted-foreground">Loading...</p>
            </div>
        );
    }

    if (error) {
        return (
            <div className="p-6">
                <p className="text-sm text-destructive">{error}</p>
            </div>
        );
    }

    return (
        <div className="p-6">
            {/* Header */}
            <div className="mb-4 flex items-center gap-4">
                <h1 className="text-2xl font-bold">Users</h1>
                {canEditUsers && (
                    <Link
                        href="/dashboard/users/create"
                        className={buttonVariants({ variant: "outline", size: "sm", className: "gap-2" })}
                    >
                        <Upload className="h-4 w-4" />
                        Create New
                    </Link>
                )}
            </div>

            {/* Users table (generated by Claude) */}
            <div className="rounded-lg border">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>User</TableHead>
                            <TableHead>Role</TableHead>
                            <TableHead>Email</TableHead>
                            <TableHead>Phone</TableHead>
                            <TableHead>Birthday</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {users.map((u) => {
                            const initials = u.name
                                .split(" ")
                                .map((n) => n[0])
                                .join("")
                                .toUpperCase()
                                .slice(0, 2);

                            return (
                                <TableRow key={u.id}>
                                    <TableCell>
                                        <div className="flex items-center gap-3">
                                            <Avatar className="h-8 w-8">
                                                <AvatarFallback className="text-xs">
                                                    {initials}
                                                </AvatarFallback>
                                            </Avatar>
                                            <span className="font-medium">{u.name}</span>
                                        </div>
                                    </TableCell>
                                    <TableCell className="capitalize">{u.role}</TableCell>
                                    <TableCell>{u.email}</TableCell>
                                    <TableCell>{u.phone || "—"}</TableCell>
                                    <TableCell>
                                        {u.birthday
                                            ? new Date(u.birthday).toLocaleDateString()
                                            : "—"}
                                    </TableCell>
                                </TableRow>
                            );
                        })}
                    </TableBody>
                </Table>
            </div>
        </div>
    );
}