"use client";

// Sidebar language toggle — flips between zh-Hant and en. (generated by Claude)
// Calls the setLocale server action to write the cookie, then router.refresh()
// so the root layout re-runs on the server with the new locale.

import { useLocale, useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { useTransition } from "react";
import { Languages } from "lucide-react";
import { setLocale } from "@/app/actions/locale";
import type { Locale } from "@/i18n/config";

interface LanguageToggleProps {
  variant?: "desktop" | "mobile";
}

export function LanguageToggle({ variant = "desktop" }: LanguageToggleProps) {
  const current = useLocale() as Locale;
  const t = useTranslations("Sidebar");
  const router = useRouter();
  const [isPending, startTransition] = useTransition();

  const next: Locale = current === "zh-Hant" ? "en" : "zh-Hant";
  // Show the language we'd switch TO so the action is obvious.
  const label = next === "zh-Hant" ? t("languageChinese") : t("languageEnglish");

  function handleClick() {
    startTransition(async () => {
      await setLocale(next);
      router.refresh();
    });
  }

  if (variant === "mobile") {
    return (
      <button
        onClick={handleClick}
        disabled={isPending}
        className="flex w-full items-center gap-3 rounded-lg px-4 py-3 text-base font-bold text-amber-100 transition-colors hover:bg-white/10 hover:text-white disabled:opacity-50"
      >
        <Languages className="h-5 w-5" />
        {label}
      </button>
    );
  }

  return (
    <button
      onClick={handleClick}
      disabled={isPending}
      className="flex w-full flex-col items-center gap-1 rounded-lg px-2 py-2.5 text-[11px] font-medium text-amber-100 transition-colors hover:bg-white/10 hover:text-white disabled:opacity-50"
    >
      <Languages className="h-5 w-5" />
      {label}
    </button>
  );
}
