"use client";

import { useEffect, useState } from "react";
import { useRouter, usePathname } from "next/navigation";
import Link from "next/link";
import { useAuth } from "@/lib/auth";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Files, Users, LogOut, CloudUpload, Layers } from "lucide-react";

const navItems = [
    { label: "Files", href: "/dashboard/files", icon: Files },
    { label: "Users", href: "/dashboard/users", icon: Users },
];

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const { user, logout, loading } = useAuth();
    const router = useRouter();
    const pathname = usePathname();
    const [mobileNavOpen, setMobileNavOpen] = useState(false);

    useEffect(() => {
        if (!loading && !user) {
            router.push("/login");
        }
    }, [user, router, loading]);

    // Close mobile nav on route change
    useEffect(() => {
        setMobileNavOpen(false);
    }, [pathname]);

    if (loading || !user) {
        return null;
    }

    function handleLogout() {
        logout();
        router.push("/login");
    }

    const initials = user.name
        .split(" ")
        .map((n) => n[0])
        .join("")
        .toUpperCase()
        .slice(0, 2);

    return (
        <div className="flex min-h-screen flex-col min-[500px]:flex-row">

            {/* ── Mobile header bar (< 500px only) ── (generated by Claude) */}
            <header className="flex items-center justify-between bg-amber-700 px-5 py-3 min-[500px]:hidden">
                <Link
                    href="/dashboard/files/create"
                    className="flex items-center gap-2 text-white"
                >
                    <CloudUpload className="h-7 w-7" />
                    <span className="text-lg font-semibold">Upload</span>
                </Link>
                <button
                    onClick={() => setMobileNavOpen((v) => !v)}
                    aria-label="Toggle navigation"
                    className="text-white"
                >
                    <Layers className="h-7 w-7" />
                </button>
            </header>

            {/* ── Mobile nav overlay (< 500px, shown when open) ── (generated by Claude) */}
            {mobileNavOpen && (
                <div className="fixed inset-0 z-50 flex flex-col bg-amber-700 min-[500px]:hidden">
                    {/* Header row mirrored inside the overlay */}
                    <div className="flex items-center justify-between px-5 py-3">
                        <Link
                            href="/dashboard/files/create"
                            className="flex items-center gap-2 text-white"
                        >
                            <CloudUpload className="h-7 w-7" />
                            <span className="text-lg font-semibold">Upload</span>
                        </Link>
                        <button
                            onClick={() => setMobileNavOpen(false)}
                            aria-label="Close navigation"
                            className="text-white"
                        >
                            <Layers className="h-7 w-7" />
                        </button>
                    </div>

                    {/* User greeting — avatar links to self profile */}
                    <div className="mt-12 flex flex-col items-center gap-3">
                        <Link href="/dashboard/me">
                            <Avatar className="h-20 w-20 border-2 border-white/20">
                                {user.avatar && (
                                    <AvatarImage src={user.avatar} alt={user.name} />
                                )}
                                <AvatarFallback className="bg-white/25 text-2xl text-white">
                                    {initials}
                                </AvatarFallback>
                            </Avatar>
                        </Link>
                        <span className="text-lg font-medium text-white">
                            Hello, {user.name.split(" ")[0]}
                        </span>
                    </div>

                    {/* Nav links — same icons as desktop sidebar */}
                    <nav className="mt-10 flex flex-col items-center gap-2 w-full px-8">
                        {navItems.map((item) => {
                            const isActive = pathname.startsWith(item.href);
                            return (
                                <Link
                                    key={item.href}
                                    href={item.href}
                                    className={`flex w-full items-center gap-3 rounded-lg px-4 py-3 text-base font-bold transition-colors ${
                                        isActive
                                            ? "bg-white/20 text-white"
                                            : "text-amber-100 hover:bg-white/10 hover:text-white"
                                    }`}
                                >
                                    <item.icon className="h-5 w-5" />
                                    {item.label}
                                </Link>
                            );
                        })}
                        <button
                            onClick={handleLogout}
                            className="flex w-full items-center gap-3 rounded-lg px-4 py-3 text-base font-bold text-amber-100 transition-colors hover:bg-white/10 hover:text-white"
                        >
                            <LogOut className="h-5 w-5" />
                            Sign out
                        </button>
                    </nav>
                </div>
            )}

            {/* ── Desktop sidebar (≥ 500px only) ── */}
            <aside className="hidden min-[500px]:flex w-20 flex-col items-center bg-amber-700 py-6 text-white">
                {/* User avatar + greeting — links to self profile */}
                <div className="flex flex-col items-center gap-1">
                    <Link href="/dashboard/me">
                        <Avatar className="h-10 w-10 border-2 border-white/30">
                            {user.avatar && (
                                <AvatarImage src={user.avatar} alt={user.name} />
                            )}
                            <AvatarFallback className="bg-amber-900 text-sm text-white">
                                {initials}
                            </AvatarFallback>
                        </Avatar>
                        <div className="mt-1 text-center text-[11px] leading-tight">
                            <div className="text-amber-200">Hello,</div>
                            <div className="font-medium">{user.name.split(" ")[0]}</div>
                        </div>
                    </Link>
                </div>

                {/* Navigation */}
                <nav className="mt-8 flex flex-col gap-1 w-full px-2">
                    {navItems.map((item) => {
                        const isActive = pathname.startsWith(item.href);
                        return (
                            <Link
                                key={item.href}
                                href={item.href}
                                className={`flex flex-col items-center gap-1 rounded-lg px-2 py-2.5 text-[11px] font-medium transition-colors ${isActive
                                        ? "bg-white/20 text-white"
                                        : "text-amber-100 hover:bg-white/10 hover:text-white"
                                    }`}
                            >
                                <item.icon className="h-5 w-5" />
                                {item.label}
                            </Link>
                        );
                    })}
                </nav>

                {/* Logout at bottom */}
                <div className="mt-auto px-2 w-full">
                    <button
                        onClick={handleLogout}
                        className="flex w-full flex-col items-center gap-1 rounded-lg px-2 py-2.5 text-[11px] font-medium text-amber-100 transition-colors hover:bg-white/10 hover:text-white"
                    >
                        <LogOut className="h-5 w-5" />
                        Sign out
                    </button>
                </div>
            </aside>

            {/* Main content */}
            <main className="flex-1 bg-muted/40 relative">{children}</main>
        </div>
    );
}